### ISSUE TITLE
msvc port?

### ISSUE THREAD

**Issue by r-lyeh-archived** [krig/roam#1]
Hello,

I have done a quick msvc (2013) port
I downgraded some C11 stuff, created a new `port.h` tiny header with specific platform code, and then bugfixed some compilation errors.

Would you like me to make a PR for it? In any case, really nice project
Keep up the good work : )

![image](https://cloud.githubusercontent.com/assets/878187/6127137/f9e14908-b127-11e4-93f4-d7558c89ed9d.png)

**Comment by krig** [comment]
Cool! That would be great, yeah. Thanks :D

**Comment by r-lyeh-archived** [comment]
sure :beer: hold on
